In [1]:
import pandas as pd
import numpy as np

In [2]:
mortality_df = pd.read_csv("Resources/mortality_county.csv")
pollution_df = pd.read_csv("Resources/pollution_clean.csv")

In [3]:
mortality_df

,Unnamed: 0,Year,ICD-10 113 Cause List,ICD-10 113 Cause List Code,County,County Code,Race,Race Code,Gender,Gender Code,Deaths,Population,Crude Rate
0,0,2006,Influenza and pneumonia (J09-J18),GR113-076,Alameda,6001.0,Asian or Pacific Islander,A-PI,Female,F,15.0,204139.0,Unreliable
1,1,2006,Influenza and pneumonia (J09-J18),GR113-076,Alameda,6001.0,Asian or Pacific Islander,A-PI,Male,M,13.0,189589.0,Unreliable
2,2,2006,Influenza and pneumonia (J09-J18),GR113-076,Alameda,6001.0,Black or African American,2054-5,Female,F,30.0,112599.0,26.6
3,3,2006,Influenza and pneumonia (J09-J18),GR113-076,Alameda,6001.0,Black or African American,2054-5,Male,M,21.0,98714.0,21.3
4,4,2006,Influenza and pneumonia (J09-J18),GR113-076,Alameda,6001.0,White,2106-3,Female,F,73.0,410372.0,17.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3768,6312,2016,"Other diseases of respiratory system (J00-J06,...",GR113-089,Santa Cruz,6087.0,White,2106-3,Male,M,13.0,122021.0,Unreliable
3769,6315,2016,"Other diseases of respiratory system (J00-J06,...",GR113-089,Solano,6095.0,White,2106-3,Female,F,12.0,136869.0,Unreliable
3770,6316,2016,"Other diseases of respiratory system (J00-J06,...",GR113-089,Solano,6095.0,White,2106-3,Male,M,14.0,139620.0,Unreliable
3771,6323,2016,"Other diseases of respiratory system (J00-J06,...",GR113-089,Ventura,6111.0,White,2106-3,Female,F,26.0,369087.0,7
3772,6324,2016,"Other diseases of respiratory system (J00-J06,...",GR113-089,Ventura,6111.0,White,2106-3,Male,M,36.0,364229.0,9.9

In [4]:
# clean mortality data years 2006 to 2010
mortality_2006_2010 = mortality_df[mortality_df["Year"] < 2011]
mortality_2006_2010

,Unnamed: 0,Year,ICD-10 113 Cause List,ICD-10 113 Cause List Code,County,County Code,Race,Race Code,Gender,Gender Code,Deaths,Population,Crude Rate
0,0,2006,Influenza and pneumonia (J09-J18),GR113-076,Alameda,6001.0,Asian or Pacific Islander,A-PI,Female,F,15.0,204139.0,Unreliable
1,1,2006,Influenza and pneumonia (J09-J18),GR113-076,Alameda,6001.0,Asian or Pacific Islander,A-PI,Male,M,13.0,189589.0,Unreliable
2,2,2006,Influenza and pneumonia (J09-J18),GR113-076,Alameda,6001.0,Black or African American,2054-5,Female,F,30.0,112599.0,26.6
3,3,2006,Influenza and pneumonia (J09-J18),GR113-076,Alameda,6001.0,Black or African American,2054-5,Male,M,21.0,98714.0,21.3
4,4,2006,Influenza and pneumonia (J09-J18),GR113-076,Alameda,6001.0,White,2106-3,Female,F,73.0,410372.0,17.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1649,2774,2010,"Other diseases of respiratory system (J00-J06,...",GR113-089,Santa Clara,6085.0,White,2106-3,Male,M,43.0,549707.0,7.8
1650,2777,2010,"Other diseases of respiratory system (J00-J06,...",GR113-089,Solano,6095.0,White,2106-3,Female,F,14.0,129084.0,Unreliable
1651,2778,2010,"Other diseases of respiratory system (J00-J06,...",GR113-089,Solano,6095.0,White,2106-3,Male,M,16.0,131796.0,Unreliable
1652,2785,2010,"Other diseases of respiratory system (J00-J06,...",GR113-089,Ventura,6111.0,White,2106-3,Female,F,28.0,359932.0,7.8
1653,2786,2010,"Other diseases of respiratory system (J00-J06,...",GR113-089,Ventura,6111.0,White,2106-3,Male,M,27.0,357841.0,7.5

In [5]:
mortality_county_ct = mortality_2006_2010["County"].unique().tolist()
print(mortality_county_ct, len(mortality_county_ct))

['Alameda', 'Contra Costa', 'Fresno', 'Humboldt', 'Kern', 'Los Angeles', 'Orange', 'Riverside', 'Sacramento', 'San Bernardino', 'San Diego', 'San Francisco', 'Santa Barbara', 'Santa Clara', 'Santa Cruz', 'Solano', 'Ventura', 'Imperial'] 18

In [6]:
mortality_2006_2010.to_csv("Resources/mortality_2006_2010.csv")

In [7]:
pollution_df

,Unnamed: 0,County,City,Year,NO2 Units,NO2 Mean,NO2 1st Max Value,NO2 1st Max Hour,NO2 AQI,O3 Units,...,SO2 Units,SO2 Mean,SO2 1st Max Value,SO2 1st Max Hour,SO2 AQI,CO Units,CO Mean,CO 1st Max Value,CO 1st Max Hour,CO AQI
0,0,Contra Costa,Concord,2000,Parts per billion,14.782609,26.0,4,25,Parts per million,...,Parts per billion,0.636364,2.0,9,3.0,Parts per million,0.556522,1.3,4,NaN
1,1,Contra Costa,Concord,2000,Parts per billion,14.782609,26.0,4,25,Parts per million,...,Parts per billion,0.636364,2.0,9,3.0,Parts per million,0.572222,0.8,6,9.0
2,2,Contra Costa,Concord,2000,Parts per billion,14.782609,26.0,4,25,Parts per million,...,Parts per billion,0.600000,2.0,11,NaN,Parts per million,0.556522,1.3,4,NaN
3,3,Contra Costa,Concord,2000,Parts per billion,14.782609,26.0,4,25,Parts per million,...,Parts per billion,0.600000,2.0,11,NaN,Parts per million,0.572222,0.8,6,9.0
4,4,Contra Costa,Concord,2000,Parts per billion,16.043478,30.0,21,28,Parts per million,...,Parts per billion,1.000000,2.0,5,3.0,Parts per million,0.578261,1.1,21,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397527,397527,Solano,Vallejo,2010,Parts per billion,11.956522,30.7,6,28,Parts per million,...,Parts per billion,0.385714,0.7,23,NaN,Parts per million,0.287500,0.5,23,6.0
397528,397528,Solano,Vallejo,2010,Parts per billion,12.943478,23.6,0,22,Parts per million,...,Parts per billion,0.834783,1.8,1,1.0,Parts per million,0.578261,1.6,1,NaN
397529,397529,Solano,Vallejo,2010,Parts per billion,12.943478,23.6,0,22,Parts per million,...,Parts per billion,0.834783,1.8,1,1.0,Parts per million,0.641667,1.2,5,14.0
397530,397530,Solano,Vallejo,2010,Parts per billion,12.943478,23.6,0,22,Parts per million,...,Parts per billion,0.757143,1.5,2,NaN,Parts per million,0.578261,1.6,1,NaN
397531,397531,Solano,Vallejo,2010,Parts per billion,12.943478,23.6,0,22,Parts per million,...,Parts per billion,0.757143,1.5,2,NaN,Parts per million,0.641667,1.2,5,14.0

In [8]:
pollution_2006_2010 = pollution_df[pollution_df["Year"] > 2005]
pollution_2006_2010

,Unnamed: 0,County,City,Year,NO2 Units,NO2 Mean,NO2 1st Max Value,NO2 1st Max Hour,NO2 AQI,O3 Units,...,SO2 Units,SO2 Mean,SO2 1st Max Value,SO2 1st Max Hour,SO2 AQI,CO Units,CO Mean,CO 1st Max Value,CO 1st Max Hour,CO AQI
216292,216292,Contra Costa,Concord,2006,Parts per billion,9.478261,21.0,2,20,Parts per million,...,Parts per billion,0.045455,1.0,18,1.0,Parts per million,0.395652,0.7,9,NaN
216293,216293,Contra Costa,Concord,2006,Parts per billion,9.478261,21.0,2,20,Parts per million,...,Parts per billion,0.045455,1.0,18,1.0,Parts per million,0.388889,0.5,6,6.0
216294,216294,Contra Costa,Concord,2006,Parts per billion,9.478261,21.0,2,20,Parts per million,...,Parts per billion,0.042857,0.3,20,NaN,Parts per million,0.395652,0.7,9,NaN
216295,216295,Contra Costa,Concord,2006,Parts per billion,9.478261,21.0,2,20,Parts per million,...,Parts per billion,0.042857,0.3,20,NaN,Parts per million,0.388889,0.5,6,6.0
216296,216296,Contra Costa,Concord,2006,Parts per billion,11.521739,20.0,8,19,Parts per million,...,Parts per billion,0.227273,2.0,5,3.0,Parts per million,0.413043,0.6,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397527,397527,Solano,Vallejo,2010,Parts per billion,11.956522,30.7,6,28,Parts per million,...,Parts per billion,0.385714,0.7,23,NaN,Parts per million,0.287500,0.5,23,6.0
397528,397528,Solano,Vallejo,2010,Parts per billion,12.943478,23.6,0,22,Parts per million,...,Parts per billion,0.834783,1.8,1,1.0,Parts per million,0.578261,1.6,1,NaN
397529,397529,Solano,Vallejo,2010,Parts per billion,12.943478,23.6,0,22,Parts per million,...,Parts per billion,0.834783,1.8,1,1.0,Parts per million,0.641667,1.2,5,14.0
397530,397530,Solano,Vallejo,2010,Parts per billion,12.943478,23.6,0,22,Parts per million,...,Parts per billion,0.757143,1.5,2,NaN,Parts per million,0.578261,1.6,1,NaN
397531,397531,Solano,Vallejo,2010,Parts per billion,12.943478,23.6,0,22,Parts per million,...,Parts per billion,0.757143,1.5,2,NaN,Parts per million,0.641667,1.2,5,14.0

In [9]:
pollution_county_ct = pollution_2006_2010["County"].unique().tolist()
print(pollution_county_ct, len(pollution_county_ct))

['Contra Costa', 'Humboldt', 'Imperial', 'Los Angeles', 'Orange', 'Riverside', 'Sacramento', 'San Bernardino', 'San Diego', 'San Francisco', 'Santa Barbara', 'Santa Cruz', 'Solano', 'Alameda', 'Fresno', 'Santa Clara'] 16

In [15]:
diseases = mortality_2006_2010["ICD-10 113 Cause List"].unique().tolist()
print(diseases, len(diseases))

['Influenza and pneumonia (J09-J18)', 'Pneumonia (J12-J18)', 'Chronic lower respiratory diseases (J40-J47)', 'Bronchitis, chronic and unspecified (J40-J42)', 'Emphysema (J43)', 'Asthma (J45-J46)', 'Other chronic lower respiratory diseases (J44,J47)', 'Pneumonitis due to solids and liquids (J69)', 'Other diseases of respiratory system (J00-J06,J30- J39,J67,J70-J98)', 'Influenza (J09-J11)'] 10

In [11]:
pollution_2006_2010.to_csv("Resources/pollution_2006_2010.csv")

In [16]:
def common_county(x, y):
    x_set = set(x)
    y_set = set(y)
    
    if len(x_set.intersection(y_set)) > 0:
        return x_set.intersection(y_set)
    else:
        return("No common county")
    
same_county = common_county(mortality_county_ct, pollution_county_ct)
print(same_county, len(same_county))

{'Orange', 'Santa Barbara', 'Solano', 'Alameda', 'Fresno', 'Santa Clara', 'Contra Costa', 'Sacramento', 'Humboldt', 'Riverside', 'San Diego', 'Imperial', 'San Francisco', 'Los Angeles', 'San Bernardino', 'Santa Cruz'} 16

In [17]:
# Making sure there are the same number of counties in Pollution and Mortality Data
mortality_2006_2010_clean = mortality_2006_2010[mortality_2006_2010["County"].isin(same_county)]
mortality_2006_2010_clean

,Unnamed: 0,Year,ICD-10 113 Cause List,ICD-10 113 Cause List Code,County,County Code,Race,Race Code,Gender,Gender Code,Deaths,Population,Crude Rate
0,0,2006,Influenza and pneumonia (J09-J18),GR113-076,Alameda,6001.0,Asian or Pacific Islander,A-PI,Female,F,15.0,204139.0,Unreliable
1,1,2006,Influenza and pneumonia (J09-J18),GR113-076,Alameda,6001.0,Asian or Pacific Islander,A-PI,Male,M,13.0,189589.0,Unreliable
2,2,2006,Influenza and pneumonia (J09-J18),GR113-076,Alameda,6001.0,Black or African American,2054-5,Female,F,30.0,112599.0,26.6
3,3,2006,Influenza and pneumonia (J09-J18),GR113-076,Alameda,6001.0,Black or African American,2054-5,Male,M,21.0,98714.0,21.3
4,4,2006,Influenza and pneumonia (J09-J18),GR113-076,Alameda,6001.0,White,2106-3,Female,F,73.0,410372.0,17.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1647,2772,2010,"Other diseases of respiratory system (J00-J06,...",GR113-089,Santa Barbara,6083.0,White,2106-3,Male,M,12.0,187873.0,Unreliable
1648,2773,2010,"Other diseases of respiratory system (J00-J06,...",GR113-089,Santa Clara,6085.0,White,2106-3,Female,F,39.0,532299.0,7.3
1649,2774,2010,"Other diseases of respiratory system (J00-J06,...",GR113-089,Santa Clara,6085.0,White,2106-3,Male,M,43.0,549707.0,7.8
1650,2777,2010,"Other diseases of respiratory system (J00-J06,...",GR113-089,Solano,6095.0,White,2106-3,Female,F,14.0,129084.0,Unreliable
1651,2778,2010,"Other diseases of respiratory system (J00-J06,...",GR113-089,Solano,6095.0,White,2106-3,Male,M,16.0,131796.0,Unreliable

In [18]:
mortality_2006_2010_clean.to_csv("Resources/mortality_2006_2010_clean.csv")