In [6]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import scipy.stats as st

In [7]:
# Importing data files
pollution_data_df = pd.read_csv("../Resources/california_pollution.csv")
mortality_data_df1 = pd.read_csv("../Resources/california_mortality_1.csv")
mortality_data_df2 = pd.read_csv("../Resources/california_mortality_2.csv")

In [8]:
pollution_data_df.head()

,Unnamed: 0,State Code,County Code,Site Num,Address,State,County,City,Date Local,NO2 Units,...,SO2 Units,SO2 Mean,SO2 1st Max Value,SO2 1st Max Hour,SO2 AQI,CO Units,CO Mean,CO 1st Max Value,CO 1st Max Hour,CO AQI
0,3516,6,13,2,2956-A TREAT BOULEVARD,California,Contra Costa,Concord,1/1/00,Parts per billion,...,Parts per billion,0.636364,2.0,9,3.0,Parts per million,0.556522,1.3,4,NaN
1,3517,6,13,2,2956-A TREAT BOULEVARD,California,Contra Costa,Concord,1/1/00,Parts per billion,...,Parts per billion,0.636364,2.0,9,3.0,Parts per million,0.572222,0.8,6,9.0
2,3518,6,13,2,2956-A TREAT BOULEVARD,California,Contra Costa,Concord,1/1/00,Parts per billion,...,Parts per billion,0.600000,2.0,11,NaN,Parts per million,0.556522,1.3,4,NaN
3,3519,6,13,2,2956-A TREAT BOULEVARD,California,Contra Costa,Concord,1/1/00,Parts per billion,...,Parts per billion,0.600000,2.0,11,NaN,Parts per million,0.572222,0.8,6,9.0
4,3520,6,13,2,2956-A TREAT BOULEVARD,California,Contra Costa,Concord,1/2/00,Parts per billion,...,Parts per billion,1.000000,2.0,5,3.0,Parts per million,0.578261,1.1,21,NaN

In [9]:
mortality_data_df1.head()

,Notes,County,County Code,Gender,Gender Code,Year,Year Code,Race,Race Code,Deaths,Population,Crude Rate,Age Adjusted Rate,% of Total Deaths
0,NaN,"Alameda County, CA",6001.0,Female,F,2006.0,2006.0,Asian or Pacific Islander,A-PI,46.0,204139.0,22.5,27.7,0.000
1,NaN,"Alameda County, CA",6001.0,Female,F,2006.0,2006.0,Black or African American,2054-5,70.0,112599.0,62.2,62.1,0.000
2,NaN,"Alameda County, CA",6001.0,Female,F,2006.0,2006.0,White,2106-3,330.0,410372.0,80.4,66.5,0.001
3,NaN,"Alameda County, CA",6001.0,Female,F,2007.0,2007.0,Asian or Pacific Islander,A-PI,42.0,209933.0,20.0,24.4,0.000
4,NaN,"Alameda County, CA",6001.0,Female,F,2007.0,2007.0,Black or African American,2054-5,69.0,112100.0,61.6,61.1,0.000

In [10]:
mortality_data_df2.head()

,Notes,County,County Code,Gender,Gender Code,Year,Year Code,Race,Race Code,Deaths,Population,Crude Rate,Age Adjusted Rate,% of Total Deaths
0,NaN,"Alameda County, CA",6001.0,Female,F,2006.0,2006.0,American Indian or Alaska Native,1002-5,17.0,9043.0,188.0 (Unreliable),364.4 (Unreliable),0.000
1,NaN,"Alameda County, CA",6001.0,Female,F,2006.0,2006.0,Asian or Pacific Islander,A-PI,667.0,204139.0,326.7,397.8,0.000
2,NaN,"Alameda County, CA",6001.0,Female,F,2006.0,2006.0,Black or African American,2054-5,1048.0,112599.0,930.7,932.3,0.000
3,NaN,"Alameda County, CA",6001.0,Female,F,2006.0,2006.0,White,2106-3,3003.0,410372.0,731.8,593.8,0.001
4,NaN,"Alameda County, CA",6001.0,Female,F,2007.0,2007.0,American Indian or Alaska Native,1002-5,19.0,9388.0,202.4 (Unreliable),351.2 (Unreliable),0.000