In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import scipy.stats as st

In [2]:
# Importing data files

pollution_data_df = pd.read_csv("Resources/California_Pollution.csv")
mortality_data_df = pd.read_csv("Resources/California_Mortality.csv")

In [3]:
pollution_data_df
# pollution_data_df.info()

,Unnamed: 0,State Code,County Code,Site Num,Address,State,County,City,Date Local,NO2 Units,...,SO2 Units,SO2 Mean,SO2 1st Max Value,SO2 1st Max Hour,SO2 AQI,CO Units,CO Mean,CO 1st Max Value,CO 1st Max Hour,CO AQI
0,3516,6,13,2,2956-A TREAT BOULEVARD,California,Contra Costa,Concord,1/1/00,Parts per billion,...,Parts per billion,0.636364,2.0,9,3.0,Parts per million,0.556522,1.3,4,NaN
1,3517,6,13,2,2956-A TREAT BOULEVARD,California,Contra Costa,Concord,1/1/00,Parts per billion,...,Parts per billion,0.636364,2.0,9,3.0,Parts per million,0.572222,0.8,6,9.0
2,3518,6,13,2,2956-A TREAT BOULEVARD,California,Contra Costa,Concord,1/1/00,Parts per billion,...,Parts per billion,0.600000,2.0,11,NaN,Parts per million,0.556522,1.3,4,NaN
3,3519,6,13,2,2956-A TREAT BOULEVARD,California,Contra Costa,Concord,1/1/00,Parts per billion,...,Parts per billion,0.600000,2.0,11,NaN,Parts per million,0.572222,0.8,6,9.0
4,3520,6,13,2,2956-A TREAT BOULEVARD,California,Contra Costa,Concord,1/2/00,Parts per billion,...,Parts per billion,1.000000,2.0,5,3.0,Parts per million,0.578261,1.1,21,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397527,44293,6,95,4,304 TUOLUMNE ST.,California,Solano,Vallejo,12/30/10,Parts per billion,...,Parts per billion,0.385714,0.7,23,NaN,Parts per million,0.287500,0.5,23,6.0
397528,44294,6,95,4,304 TUOLUMNE ST.,California,Solano,Vallejo,12/31/10,Parts per billion,...,Parts per billion,0.834783,1.8,1,1.0,Parts per million,0.578261,1.6,1,NaN
397529,44295,6,95,4,304 TUOLUMNE ST.,California,Solano,Vallejo,12/31/10,Parts per billion,...,Parts per billion,0.834783,1.8,1,1.0,Parts per million,0.641667,1.2,5,14.0
397530,44296,6,95,4,304 TUOLUMNE ST.,California,Solano,Vallejo,12/31/10,Parts per billion,...,Parts per billion,0.757143,1.5,2,NaN,Parts per million,0.578261,1.6,1,NaN
397531,44297,6,95,4,304 TUOLUMNE ST.,California,Solano,Vallejo,12/31/10,Parts per billion,...,Parts per billion,0.757143,1.5,2,NaN,Parts per million,0.641667,1.2,5,14.0

In [4]:
mortality_data_df

,Notes,Year,Year Code,ICD-10 113 Cause List,ICD-10 113 Cause List Code,County,County Code,Race,Race Code,Gender,Gender Code,Deaths,Population,Crude Rate
0,NaN,2006.0,2006.0,#Influenza and pneumonia (J09-J18),GR113-076,"Alameda County, CA",6001.0,Asian or Pacific Islander,A-PI,Female,F,15.0,204139.0,Unreliable
1,NaN,2006.0,2006.0,#Influenza and pneumonia (J09-J18),GR113-076,"Alameda County, CA",6001.0,Asian or Pacific Islander,A-PI,Male,M,13.0,189589.0,Unreliable
2,NaN,2006.0,2006.0,#Influenza and pneumonia (J09-J18),GR113-076,"Alameda County, CA",6001.0,Black or African American,2054-5,Female,F,30.0,112599.0,26.6
3,NaN,2006.0,2006.0,#Influenza and pneumonia (J09-J18),GR113-076,"Alameda County, CA",6001.0,Black or African American,2054-5,Male,M,21.0,98714.0,21.3
4,NaN,2006.0,2006.0,#Influenza and pneumonia (J09-J18),GR113-076,"Alameda County, CA",6001.0,White,2106-3,Female,F,73.0,410372.0,17.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6390,resident population that is under one year of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6391,"7. Beginning with the 2018 data, changes have ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6392,"compared to previous practice. In addition, da...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6393,in information available to individual states ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6394,information can be found at: https://www.cdc.g...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
mortality_data_df['County'] = mortality_data_df['County'].str.split(' ').str[0]
mortality_data_df
mortality_data_df.info()
# mortality_data_df[["County","State_Abbreviation"]] = mortality_data_df.County.str.split(" ",expand=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6395 entries, 0 to 6394
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Notes                       70 non-null     object
 1   Year                        6325 non-null   float64
 2   Year Code                   6325 non-null   float64
 3   ICD-10 113 Cause List       6325 non-null   object
 4   ICD-10 113 Cause List Code  6325 non-null   object
 5   County                      6325 non-null   object
 6   County Code                 6325 non-null   float64
 7   Race                        6325 non-null   object
 8   Race Code                   6325 non-null   object
 9   Gender                      6325 non-null   object
 10  Gender Code                 6325 non-null   object
 11  Deaths                      6325 non-null   float64
 12  Population                  6325 non-null   float64
 13  Crude Rate                  6325 non-null   object
 14  State_Abbreviation          6325 non-null   object
dtypes: float64(5), object(10)
memory usage: 749.5+ KB

In [18]:
mortality_data_clean_df = mortality_data_df.drop(["Notes"], axis=1)
mortality_data_clean_df.dropna(how='all')
mortality_data_clean_df

,Year,Year Code,ICD-10 113 Cause List,ICD-10 113 Cause List Code,County,County Code,Race,Race Code,Gender,Gender Code,Deaths,Population,Crude Rate,State_Abbreviation
0,2006.0,2006.0,#Influenza and pneumonia (J09-J18),GR113-076,Alameda,6001.0,Asian or Pacific Islander,A-PI,Female,F,15.0,204139.0,Unreliable,CA
1,2006.0,2006.0,#Influenza and pneumonia (J09-J18),GR113-076,Alameda,6001.0,Asian or Pacific Islander,A-PI,Male,M,13.0,189589.0,Unreliable,CA
2,2006.0,2006.0,#Influenza and pneumonia (J09-J18),GR113-076,Alameda,6001.0,Black or African American,2054-5,Female,F,30.0,112599.0,26.6,CA
3,2006.0,2006.0,#Influenza and pneumonia (J09-J18),GR113-076,Alameda,6001.0,Black or African American,2054-5,Male,M,21.0,98714.0,21.3,CA
4,2006.0,2006.0,#Influenza and pneumonia (J09-J18),GR113-076,Alameda,6001.0,White,2106-3,Female,F,73.0,410372.0,17.8,CA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6391,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6393,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
merged_df = mortality_data_df.combine_first(pollution_data_df)
merged_df.to_csv("test2.csv")
print(merged_df)

PermissionError: [Errno 13] Permission denied

In [9]:
# Combine the data into a single dataset
# merged_inner = pd.merge(left=mortality_data_df, right=pollution_data_df, left_on='County', right_on='County')
# merged_inner = pd.merge(mortality_data_df, pollution_data_df, how="outer", on=["County"])
# merged_inner
# merged_inner.to_csv('merged_inner.csv')
# merged_inner

,Notes,Year,Year Code,ICD-10 113 Cause List,ICD-10 113 Cause List Code,County,County Code_x,Race,Race Code,Gender,...,SO2 Units,SO2 Mean,SO2 1st Max Value,SO2 1st Max Hour,SO2 AQI,CO Units,CO Mean,CO 1st Max Value,CO 1st Max Hour,CO AQI
0,NaN,2006.0,2006.0,#Influenza and pneumonia (J09-J18),GR113-076,Alameda County,6001.0,Asian or Pacific Islander,A-PI,Female,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2006.0,2006.0,#Influenza and pneumonia (J09-J18),GR113-076,Alameda County,6001.0,Asian or Pacific Islander,A-PI,Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2006.0,2006.0,#Influenza and pneumonia (J09-J18),GR113-076,Alameda County,6001.0,Black or African American,2054-5,Female,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,2006.0,2006.0,#Influenza and pneumonia (J09-J18),GR113-076,Alameda County,6001.0,Black or African American,2054-5,Male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,2006.0,2006.0,#Influenza and pneumonia (J09-J18),GR113-076,Alameda County,6001.0,White,2106-3,Female,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403922,NaN,NaN,NaN,NaN,NaN,Santa Clara,NaN,NaN,NaN,NaN,...,Parts per billion,0.342857,0.5,11.0,NaN,Parts per million,0.420833,0.6,23.0,7.0
403923,NaN,NaN,NaN,NaN,NaN,Santa Clara,NaN,NaN,NaN,NaN,...,Parts per billion,0.456522,0.6,11.0,0.0,Parts per million,0.521739,0.7,18.0,NaN
403924,NaN,NaN,NaN,NaN,NaN,Santa Clara,NaN,NaN,NaN,NaN,...,Parts per billion,0.456522,0.6,11.0,0.0,Parts per million,0.529167,0.6,0.0,7.0
403925,NaN,NaN,NaN,NaN,NaN,Santa Clara,NaN,NaN,NaN,NaN,...,Parts per billion,0.414286,0.5,11.0,NaN,Parts per million,0.521739,0.7,18.0,NaN
403926,NaN,NaN,NaN,NaN,NaN,Santa Clara,NaN,NaN,NaN,NaN,...,Parts per billion,0.414286,0.5,11.0,NaN,Parts per million,0.529167,0.6,0.0,7.0